### ISSUE TITLE
Consider having inline tags eat their whitespace

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-htmltools#1]
@jcheng5 mentioned in review that `tag(.noWS=...)` is a historical artifact (a compromise for maintaining backwards compatibility) that we might be able to avoid by doing the right thing (i.e., having inline tags eat their whitespace) by default. For example, the current writing logic will do:

```python
>>> print(div("Hello", a("link", href = "#"), "."))
<div>
  Hello
  <a href="#">link</a>
  .
</div>
```

But what you'd really want is:

```html
<div>
  Hello<a href="#">link</a>.
</div>
```

[Here's a list of inline elements](https://www.w3schools.com/html/html_blocks.asp) that we could do this for, but will the fact that you can change `inline`/`block` display via CSS introduce issues?

**Comment by jcheng5** [comment]
Implemented in https://github.com/posit-dev/py-htmltools/pull/54
